### ISSUE TITLE
Prevent repeating the last quote

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Advice_Me#12]
Hey!

As the project grows, it is quite unlikely that quotes will be repeated but in the first versions, where there were few quotes, they could be repeated.

I mean, sometimes the user press the button to get a quote and it said: "Keep strong", and, when the user press again, the script just take another random quote but this can me maybe the same and show again: "Keep strong".

I would like the script to detect if the quote has just been printed and choose another in case the quote is the same

**Comment by Megatank58** [comment]
Hello i would like to do this, can you assign it to me

**Comment by Megatank58** [comment]
Hello I have opened #13 which fixes this
