### ISSUE TITLE
Make the action only when click button

### ISSUE THREAD

**Issue by fcoterroba** [fcoterroba/Advice_Me#14]
Hey!

Riight now, the plugin provides you a quote everytime you click it, wherever you want. But I think it should display a new quote ONLY when you click on the button. So, if you click in the text, it won't be modified

**Comment by Harsh-Singh-Rajput** [comment]
@fcoterroba should i work on this?

**Comment by Harsh-Singh-Rajput** [comment]
@fcoterroba  i fixed the issue and made a pr please check and merge it
